# Generated by Django 4.2.5 on 2023-12-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50)),
                ('re_password', models.CharField(max_length=50)),
                ('laptop', models.CharField(max_length=255)),
                ('re_laptop', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=70)),
                ('about', models.TextField()),
                ('textarea', models.CharField(max_length=50)),
                ('checkbox', models.CharField(max_length=50)),
                ('ram', models.IntegerField()),
                ('ssd', models.CharField(max_length=50)),
                ('youtube_chanel', models.BooleanField()),
            ],
        ),
    ]
